pipeline {
    agent {
        label 'linux'
    }
    options {
        timestamps()
        ansiColor('xterm')
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }
    stages {
        stage('Create jobs') {
            when {
                anyOf {
                    changeset "dsl/**"
                    triggeredBy 'UserIdCause'
                }
            }

            steps {
                jobDsl(
                    removedViewAction: 'DELETE',
                    removedJobAction: 'DELETE',
                    targets: [
                        'dsl/scripts/*.groovy'
                    ].join("\n"),
                    unstableOnDeprecation: true,
                    sandbox: false,
                )
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}